data->list->array->series->dataframe<br>
<h3>Numpy</h3>

In [1]:
import numpy as np

In [26]:
contohList = [1,"jeruk",4, 6.589]
contohList1 = [2,"jambu",5, 8.589]
contohArray = np.array(contohList+contohList1)

In [15]:
contohList

[1, 'jeruk', 4, 6.589]

In [27]:
contohArray

array(['1', 'jeruk', '4', '6.589', '2', 'jambu', '5', '8.589'],
      dtype='<U21')

In [61]:
datas=np.arange(0,25)
datas

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [52]:
np.random.randint(0,100, 102)

array([38, 28,  7, 53, 60, 34, 94, 57, 69, 78, 61, 74, 40, 37, 61, 40, 25,
       60, 77,  4, 27, 90, 88,  0, 63, 52, 17, 55, 32, 87, 23, 35, 49, 99,
       99, 33, 66, 62, 22, 56, 54, 43, 81, 81, 51, 26, 68, 97, 95, 14, 68,
       52, 62, 50,  1,  5, 21, 64, 54, 39, 89, 89, 53, 39, 17, 38, 41, 94,
       57, 29,  3, 59, 63,  6, 64, 92, 32, 90, 53, 62, 83, 38, 42, 96, 77,
       73, 55,  0, 84, 29, 79,  7, 74, 37, 72,  8, 94, 31, 93, 18, 63, 10])

In [66]:
datasBaru=datas.reshape(5,5)
datasBaru

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
datasBaru.max()

24

In [68]:
datasBaru.min()

0

In [69]:
datasBaru.sum()

300

In [70]:
datasBaru.mean()

12.0

In [73]:
datasBaru[1,2]

7

In [78]:
datasBaru[1:5]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [80]:
datasBaru

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [79]:
datasBaru+datasBaru

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [81]:
datasBaru-datasBaru

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [82]:
datasBaru/datasBaru

<ipython-input-82-b48bfae41866>:1: RuntimeWarning: invalid value encountered in true_divide
  datasBaru/datasBaru


array([[nan,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [83]:
datasBaru*datasBaru

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]])

In [84]:
datasBaru**datasBaru

array([[                   1,                    1,                    4,
                          27,                  256],
       [                3125,                46656,               823543,
                    16777216,            387420489],
       [         10000000000,         285311670611,        8916100448256,
             302875106592253,    11112006825558016],
       [  437893890380859375,                    0, -2863221430593058543,
         -497033925936021504,  6353754964178307979],
       [-2101438300051996672, -1595931050845505211,  4981753131911086080,
         8450172506621111015,                    0]])